# Generated by Django 3.2 on 2022-01-19 17:29

from django.conf import settings
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('driver', models.ForeignKey(on_delete=models.SET(products.models.get_company_default_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
